import { GoogleTagManager } from "@next/third-parties/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/component/ui/theme-provider";
import { WebVitals } from "@/component/ui/web-vitals";
import Nav from "@/component/nav";
import { headers } from "next/headers";
import type { Metadata } from "next";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: LayoutProps<"/">) {
  const headerStore = await headers();
  const nonce = headerStore.get("x-nonce") ?? "";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <ThemeProvider>{props.children}</ThemeProvider>
        <GoogleTagManager
          gtmId={process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID ?? ""}
          nonce={nonce}
        />

        <WebVitals />
      </body>
    </html>
  );
}
