{
 "title": "RED Metrics (classic histogram)",
 "description": "request rate, error rate, duration",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "serviceName", "label": "Service Name", "query": { "query": "label_values(service_name)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# RED Metrics: (r)equest rate, (e)rror rate, (d)uration\n\nThis dashboard uses explicit bucket histograms and the stable [OpenTelemetry metrics semantic conventions](https://opentelemetry.io/docs/specs/semconv/general/metrics/).\nTo enable this for the [OpenTelemetry Java instrumentation agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation/), set the following environment variables:\n\n```\nexport OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION=explicit_bucket_histogram\n```"
   }
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_request_duration_seconds_count\", service_name=~\"$serviceName\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_request_duration_seconds_count\", service_name=~\"$serviceName\", http_response_status_code=~\"5..\"}[5m])) / sum(rate({__name__=~\"http_request_duration_seconds_count\", service_name=~\"$serviceName\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration histogram (s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (rate({__name__=~\"http_request_duration_seconds_bucket\", service_name=~\"$serviceName\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(le) (rate({__name__=~\"http_request_duration_seconds_bucket\", service_name=~\"$serviceName\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate({__name__=~\"http_request_duration_seconds_bucket\", service_name=~\"$serviceName\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate({__name__=~\"http_request_duration_seconds_bucket\", service_name=~\"$serviceName\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}