{
 "title": "MLT Erroring Endpoints",
 "tags": [
  "hono-poc",
  "app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", http_target!~\"/debug/pprof.*\"}, http_target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error Rates (Last 1 mins)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_target) (rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", http_target!~\"/debug/pprof.*\", status_code=\"STATUS_CODE_ERROR\", http_target=~\"$endpoint\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 (Last 1 mins)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by(http_target, le) (rate(traces_spanmetrics_latency_bucket{span_kind=\"SPAN_KIND_SERVER\", http_target!~\"/debug/pprof.*\", status_code=\"STATUS_CODE_ERROR\", http_target=~\"$endpoint\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Cause: Errors",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.http.target =~ \"$endpoint\" && kind = server} >> { status = error } | select(span.db.name, span.db.statement)"
    }
   ]
  }
 ]
}