{
 "title": "MLT Dashboard",
 "tags": [
  "effect-app-monorepo",
  "app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "httpStatus",
    "label": "HTTP Status",
    "query": {}
   },
   {
    "name": "httpEndpoint",
    "label": "HTTP Endpoint",
    "query": {}
   },
   {
    "name": "serviceVersion",
    "label": "Service Version",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latency per HTTP Endpoint (Last 1 mins)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_target) (rate(traces_spanmetrics_latency_sum{http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[1m])) / sum by(http_target) (rate(traces_spanmetrics_latency_count{http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Overall Error Percentage (Last 5 mins)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[5m])) / sum(rate(traces_spanmetrics_calls_total{status_code!=\"\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Target (Last 5 mins)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(http_target) (rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[5m])) / sum by(http_target) (rate(traces_spanmetrics_calls_total{status_code!=\"\",http_target=~\"${httpEndpoint}\",service_version=~\"${serviceVersion}\"}[5m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes by HTTP Endpoint (Last 10 mins)",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(http_status_code, http_target, service_version) (rate(traces_spanmetrics_calls_total{http_status_code=~\"${httpStatus}\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint Latencies Over Last Minute (Last 1 mins)",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by(http_method, http_target, service_version) (rate(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[1m]) / rate(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[1m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in Second (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "sum by(http_method, http_target) (rate(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[10m]) / rate(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\"${httpEndpoint}\", service_version=~\"${serviceVersion}\"}[10m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies in Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Auto Logged Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{service_name=\"backend\"} | logfmt | detected_level=\"error\""
    }
   ]
  }
 ]
}