{
 "title": "Traces in Dashboards",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dashTraceID", "label": "Trace ID" },
   {
    "name": "httpMethod",
    "label": "HTTP Method",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Calls total by HTTP Method (Last 1 mins)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_method) (rate(traces_spanmetrics_calls_total{service=\"backend\", http_method=~\"${httpMethod}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Logs by HTTP Method",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"backend\"} |~ \"http.method=${httpMethod}\""
    }
   ]
  },
  {
   "title": "Selected Trace",
   "type": "traces",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "c50ad6ea", "operator": "=", "scope": "span" }
     ],
     "groupBy": [
      { "id": "aa0005e2", "scope": "span" }
     ],
     "limit": 20,
     "query": "${dashTraceID}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces by HTTP Method",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "limit": 20,
     "query": "{ .service.name = \"backend\" && .http.method=~\"${httpMethod}\" }",
     "tableType": "traces"
    }
   ]
  }
 ]
}