import { GoogleTagManager } from "@next/third-parties/google";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ThemeProvider from "@/component/ui/theme-provider";
import { WebVitals } from "@/component/ui/web-vitals";
import Nav from "@/component/nav";
import { headers } from "next/headers";
import type { Metadata } from "next";
import type { Product, WithContext } from "schema-dts";
import { NextIntlClientProvider } from "next-intl";
import LocaleSwitcher from "@/component/ui/locale-switcher";
import { getLocale } from "next-intl/server";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  metadataBase: new URL("http://localhost:3002"),
  openGraph: {
    description: "Generated by create next app",
    images: "/opengraph-image",
    siteName: "Create Next App",
    title: "Create Next App",
  },
  robots: "follow, index",
  title: "Create Next App",
  twitter: {
    card: "summary_large_image",
    description: "Generated by create next app",
    images: "/twitter-image",
    site: "Create Next App",
    title: "Create Next App",
  },
};

export default async function RootLayout({
  children,
}: LayoutProps<"/[locale]">) {
  const jsonLd: WithContext<Product> = {
    "@context": "https://schema.org",
    "@type": "Product",
    description: "Generated by create next app",
    image: "/icon",
    name: "Create Next App",
  };
  const locale = await getLocale();
  const headerStore = await headers();
  const nonce = headerStore.get("x-nonce") ?? "";

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <ThemeProvider>
            <LocaleSwitcher />
            <Nav />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
        <GoogleTagManager
          gtmId={process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID ?? ""}
          nonce={nonce}
        />
        <WebVitals />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
          }}
        />
      </body>
    </html>
  );
}
