import { GoogleTagManager } from "@next/third-parties/google";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { WebVitals } from "@/components/web-vitals";
import { headers } from "next/headers";
import type { Metadata } from "next";
import type { Product, WithContext } from "schema-dts";
import { NextIntlClientProvider } from "next-intl";
import LocaleSwitcher from "@/components/locale-switcher";
import { getLocale } from "next-intl/server";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  metadataBase: new URL("http://127.0.0.1:3002"),
  openGraph: {
    description: "Generated by create next app",
    images: "/opengraph-image",
    siteName: "Create Next App",
    title: "Create Next App",
  },
  title: "Create Next App",
  twitter: {
    card: "summary_large_image",
    description: "Generated by create next app",
    images: "/twitter-image",
    site: "Create Next App",
    title: "Create Next App",
  },
};

export default async function RootLayout({
  children,
}: LayoutProps<"/[locale]">) {
  const jsonLd: WithContext<Product> = {
    "@context": "https://schema.org",
    "@type": "Product",
    description: "Generated by create next app",
    image: "/icon",
    name: "Create Next App",
  };
  const locale = await getLocale();
  const nonce = (await headers()).get("x-nonce") ?? "";

  return (
    <html
      dir={locale === "fa" ? "rtl" : "ltr"}
      lang={locale}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <NextIntlClientProvider>
            <Toaster
              position={locale === "fa" ? "bottom-left" : "bottom-right"}
            />
            <ModeToggle />
            <LocaleSwitcher />
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
        <GoogleTagManager
          gtmId={process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID ?? ""}
          nonce={nonce}
        />
        <WebVitals />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
          }}
        />
      </body>
    </html>
  );
}
